/* GENERATED by training/RL/tools/b1kconv (`b1kconv header`). Do not edit.
 * RASC v1: one little-endian file per BEHAVIOR scene. Sections are 64-byte aligned;
 * a section is an array of the record below (or u8 / u16 / f32 / bit arrays).
 *   STRINGS        char[]  NUL-terminated names; records hold byte offsets
 *   ROOM_GRID      u8[grid_h][grid_w]  RoomRec index + 1 (0 = no room), majority of 10x10 pixels
 *   TRAV*          bits[grid_h*grid_w] (bit i = byte i>>3, bit i&7): 1 = all 100 pixels free
 *                  TRAV = floor_trav_0, TRAV_NO_OBJ = floor_trav_no_obj_0 (walls only),
 *                  TRAV_NO_DOOR = floor_trav_no_door_0, TRAV_OPEN_DOOR = floor_trav_open_door_0
 *   JOINTS         f32 pool (joint positions)
 *   CANDS, REMOVED u16 pools; IN_ROOMS u32 pool (string offsets)
 */
#pragma once
#include <stdint.h>
#include <stddef.h>
#ifdef __cplusplus
#define RASC_STATIC_ASSERT(c, m) static_assert(c, m)
#else
#define RASC_STATIC_ASSERT(c, m) _Static_assert(c, m)
#endif

#define RASC_MAGIC 0x43534152u
#define RASC_VERSION 2u
#define RASC_LAYOUT_HASH 0xb8525ff4u

/* section table entry */
typedef struct RascSec {
    uint64_t offset; /* byte offset from file start (64-aligned) */
    uint64_t bytes; /* section size in bytes */
    uint32_t count; /* number of elements */
    uint32_t elem; /* element size in bytes (sizeof record, 1 for u8, 0 for bit arrays where count = bits) */
} RascSec;
RASC_STATIC_ASSERT(sizeof(RascSec) == 24, "RascSec size");
RASC_STATIC_ASSERT(offsetof(RascSec, offset) == 0, "RascSec.offset");
RASC_STATIC_ASSERT(offsetof(RascSec, bytes) == 8, "RascSec.bytes");
RASC_STATIC_ASSERT(offsetof(RascSec, count) == 16, "RascSec.count");
RASC_STATIC_ASSERT(offsetof(RascSec, elem) == 20, "RascSec.elem");

/* file header (one per file, at offset 0) */
typedef struct RascFileHeader {
    uint32_t magic; /* 'RASC' = 0x43534152 */
    uint32_t version; /* format version (1) */
    uint32_t header_bytes; /* sizeof(FileHeader) */
    uint32_t layout_hash; /* FNV-1a of the generated layout text; must equal RASC_LAYOUT_HASH */
    uint8_t scene_name[32]; /* scene model name, NUL padded */
    uint32_t scene_index; /* 0..6 (doc 1.2 order: HSF HDL HDU RD RS HSL OCR) */
    uint32_t n_levels; /* floors (levels) in this scene model; all 2026 scenes have 1 (level id 0) */
    float origin[2]; /* world xy (m) of the lower-left corner of grid cell (row 0, col 0) */
    float cell; /* grid cell size (m), 0.10 */
    uint32_t grid_w; /* grid columns (x) */
    uint32_t grid_h; /* grid rows (y); cell (r,c) center = origin + ((c+.5)*cell, (r+.5)*cell) */
    uint32_t src_px; /* layout PNG width = height (pixels) */
    float src_res; /* layout PNG resolution (m/pixel), 0.01; PNG pixel (r,c) sits at ((c-src_px/2)*res, (r-src_px/2)*res) */
    float trav_area_m2; /* free pixels of floor_trav_0.png * res^2 (full resolution) */
    uint32_t n_rooms_png; /* distinct non-zero room ids in floor_insseg_0.png at full resolution */
    uint32_t flags; /* reserved (0) */
    RascSec sections[28]; /* section table, indexed by RASC_SEC_* */
    uint32_t reserved[4]; /* 0 */
} RascFileHeader;
RASC_STATIC_ASSERT(sizeof(RascFileHeader) == 784, "RascFileHeader size");
RASC_STATIC_ASSERT(offsetof(RascFileHeader, magic) == 0, "RascFileHeader.magic");
RASC_STATIC_ASSERT(offsetof(RascFileHeader, version) == 4, "RascFileHeader.version");
RASC_STATIC_ASSERT(offsetof(RascFileHeader, header_bytes) == 8, "RascFileHeader.header_bytes");
RASC_STATIC_ASSERT(offsetof(RascFileHeader, layout_hash) == 12, "RascFileHeader.layout_hash");
RASC_STATIC_ASSERT(offsetof(RascFileHeader, scene_name) == 16, "RascFileHeader.scene_name");
RASC_STATIC_ASSERT(offsetof(RascFileHeader, scene_index) == 48, "RascFileHeader.scene_index");
RASC_STATIC_ASSERT(offsetof(RascFileHeader, n_levels) == 52, "RascFileHeader.n_levels");
RASC_STATIC_ASSERT(offsetof(RascFileHeader, origin) == 56, "RascFileHeader.origin");
RASC_STATIC_ASSERT(offsetof(RascFileHeader, cell) == 64, "RascFileHeader.cell");
RASC_STATIC_ASSERT(offsetof(RascFileHeader, grid_w) == 68, "RascFileHeader.grid_w");
RASC_STATIC_ASSERT(offsetof(RascFileHeader, grid_h) == 72, "RascFileHeader.grid_h");
RASC_STATIC_ASSERT(offsetof(RascFileHeader, src_px) == 76, "RascFileHeader.src_px");
RASC_STATIC_ASSERT(offsetof(RascFileHeader, src_res) == 80, "RascFileHeader.src_res");
RASC_STATIC_ASSERT(offsetof(RascFileHeader, trav_area_m2) == 84, "RascFileHeader.trav_area_m2");
RASC_STATIC_ASSERT(offsetof(RascFileHeader, n_rooms_png) == 88, "RascFileHeader.n_rooms_png");
RASC_STATIC_ASSERT(offsetof(RascFileHeader, flags) == 92, "RascFileHeader.flags");
RASC_STATIC_ASSERT(offsetof(RascFileHeader, sections) == 96, "RascFileHeader.sections");
RASC_STATIC_ASSERT(offsetof(RascFileHeader, reserved) == 768, "RascFileHeader.reserved");

/* object category (OmniGibson category name) used by this scene or its tasks */
typedef struct RascCatRec {
    uint32_t name; /* string offset */
    uint32_t flags; /* 1 = avg_category_specs.json has this category */
    float mass; /* category average mass (kg), avg_category_specs.json; NaN if absent */
    float volume; /* category average volume (m^3); NaN if absent */
    float density; /* category average density (kg/m^3); NaN if absent */
    uint32_t n_scene; /* scene objects of this category */
    uint32_t reserved[2]; /* 0 */
} RascCatRec;
RASC_STATIC_ASSERT(sizeof(RascCatRec) == 32, "RascCatRec size");
RASC_STATIC_ASSERT(offsetof(RascCatRec, name) == 0, "RascCatRec.name");
RASC_STATIC_ASSERT(offsetof(RascCatRec, flags) == 4, "RascCatRec.flags");
RASC_STATIC_ASSERT(offsetof(RascCatRec, mass) == 8, "RascCatRec.mass");
RASC_STATIC_ASSERT(offsetof(RascCatRec, volume) == 12, "RascCatRec.volume");
RASC_STATIC_ASSERT(offsetof(RascCatRec, density) == 16, "RascCatRec.density");
RASC_STATIC_ASSERT(offsetof(RascCatRec, n_scene) == 20, "RascCatRec.n_scene");
RASC_STATIC_ASSERT(offsetof(RascCatRec, reserved) == 24, "RascCatRec.reserved");

/* room instance (floor_insseg / floor_semseg) */
typedef struct RascRoomRec {
    uint32_t name; /* string offset: OmniGibson room instance name, e.g. 'kitchen_0' (same naming as SegmentationMap) */
    uint16_t sem; /* room category id: 1-based line of room_categories.txt */
    uint16_t ins; /* pixel value in floor_insseg_0.png */
    uint16_t og_named; /* 1 if OmniGibson (0.10 m nearest resize) names this room; 0 = only visible at full resolution */
    uint16_t reserved0; /* 0 */
    uint32_t n_cells; /* grid cells whose majority room is this room */
    float area_m2; /* pixels * res^2 at full resolution */
    float centroid[2]; /* world xy (m), full resolution */
    float bmin[2]; /* world xy min (m) */
    float bmax[2]; /* world xy max (m) */
    uint32_t reserved1; /* 0 */
} RascRoomRec;
RASC_STATIC_ASSERT(sizeof(RascRoomRec) == 48, "RascRoomRec size");
RASC_STATIC_ASSERT(offsetof(RascRoomRec, name) == 0, "RascRoomRec.name");
RASC_STATIC_ASSERT(offsetof(RascRoomRec, sem) == 4, "RascRoomRec.sem");
RASC_STATIC_ASSERT(offsetof(RascRoomRec, ins) == 6, "RascRoomRec.ins");
RASC_STATIC_ASSERT(offsetof(RascRoomRec, og_named) == 8, "RascRoomRec.og_named");
RASC_STATIC_ASSERT(offsetof(RascRoomRec, reserved0) == 10, "RascRoomRec.reserved0");
RASC_STATIC_ASSERT(offsetof(RascRoomRec, n_cells) == 12, "RascRoomRec.n_cells");
RASC_STATIC_ASSERT(offsetof(RascRoomRec, area_m2) == 16, "RascRoomRec.area_m2");
RASC_STATIC_ASSERT(offsetof(RascRoomRec, centroid) == 20, "RascRoomRec.centroid");
RASC_STATIC_ASSERT(offsetof(RascRoomRec, bmin) == 28, "RascRoomRec.bmin");
RASC_STATIC_ASSERT(offsetof(RascRoomRec, bmax) == 36, "RascRoomRec.bmax");
RASC_STATIC_ASSERT(offsetof(RascRoomRec, reserved1) == 44, "RascRoomRec.reserved1");

/* scene object (every entry of <scene>_best.json, file order) */
typedef struct RascObjRec {
    uint32_t name; /* string offset: OmniGibson object name */
    uint32_t model; /* string offset: model id */
    uint16_t cat; /* index into CatRec */
    uint16_t room_a; /* first in_rooms entry (RoomRec index) or 0xFFFF */
    uint16_t room_b; /* second in_rooms entry (doors) or 0xFFFF */
    uint16_t level; /* floor/level id (0) */
    uint32_t flags; /* RASC_F_* */
    uint16_t n_joints; /* joint_pos length in the scene state */
    uint16_t n_in_rooms; /* in_rooms entries (all, also unresolved ones) in the IN_ROOMS pool */
    uint32_t joint_off; /* first joint in the JOINTS pool */
    float pos[3]; /* root link position (m) */
    float quat[4]; /* root link orientation (x, y, z, w) */
    float scale[3]; /* instance scale */
    float center[3]; /* world bbox center = pos + R * (scale * base_link_offset) */
    float half[3]; /* bbox half extents in the object frame = scale * bbox_size / 2 */
    float aabb_min[3]; /* world axis-aligned box of the rotated bbox */
    float aabb_max[3];
    float yaw; /* rotation about z (rad) from quat */
    float mass; /* category average mass (kg) or NaN */
    uint32_t in_rooms_off; /* first entry in IN_ROOMS (u32 string offsets of the in_rooms names) */
} RascObjRec;
RASC_STATIC_ASSERT(sizeof(RascObjRec) == 128, "RascObjRec size");
RASC_STATIC_ASSERT(offsetof(RascObjRec, name) == 0, "RascObjRec.name");
RASC_STATIC_ASSERT(offsetof(RascObjRec, model) == 4, "RascObjRec.model");
RASC_STATIC_ASSERT(offsetof(RascObjRec, cat) == 8, "RascObjRec.cat");
RASC_STATIC_ASSERT(offsetof(RascObjRec, room_a) == 10, "RascObjRec.room_a");
RASC_STATIC_ASSERT(offsetof(RascObjRec, room_b) == 12, "RascObjRec.room_b");
RASC_STATIC_ASSERT(offsetof(RascObjRec, level) == 14, "RascObjRec.level");
RASC_STATIC_ASSERT(offsetof(RascObjRec, flags) == 16, "RascObjRec.flags");
RASC_STATIC_ASSERT(offsetof(RascObjRec, n_joints) == 20, "RascObjRec.n_joints");
RASC_STATIC_ASSERT(offsetof(RascObjRec, n_in_rooms) == 22, "RascObjRec.n_in_rooms");
RASC_STATIC_ASSERT(offsetof(RascObjRec, joint_off) == 24, "RascObjRec.joint_off");
RASC_STATIC_ASSERT(offsetof(RascObjRec, pos) == 28, "RascObjRec.pos");
RASC_STATIC_ASSERT(offsetof(RascObjRec, quat) == 40, "RascObjRec.quat");
RASC_STATIC_ASSERT(offsetof(RascObjRec, scale) == 56, "RascObjRec.scale");
RASC_STATIC_ASSERT(offsetof(RascObjRec, center) == 68, "RascObjRec.center");
RASC_STATIC_ASSERT(offsetof(RascObjRec, half) == 80, "RascObjRec.half");
RASC_STATIC_ASSERT(offsetof(RascObjRec, aabb_min) == 92, "RascObjRec.aabb_min");
RASC_STATIC_ASSERT(offsetof(RascObjRec, aabb_max) == 104, "RascObjRec.aabb_max");
RASC_STATIC_ASSERT(offsetof(RascObjRec, yaw) == 116, "RascObjRec.yaw");
RASC_STATIC_ASSERT(offsetof(RascObjRec, mass) == 120, "RascObjRec.mass");
RASC_STATIC_ASSERT(offsetof(RascObjRec, in_rooms_off) == 124, "RascObjRec.in_rooms_off");

/* static collision box: every scene object except floors and ceilings (walls included, flagged) */
typedef struct RascBoxRec {
    float center[3]; /* world center (m) */
    float half[3]; /* half extents in the object frame */
    float yaw; /* rotation about z (rad); see RASC_F_TILTED for non-upright objects */
    uint16_t cat; /* CatRec index */
    uint16_t room; /* RoomRec index or 0xFFFF */
    uint32_t flags; /* RASC_F_* */
    uint32_t obj; /* ObjRec index */
    float zmin; /* world AABB z min */
    float zmax; /* world AABB z max */
} RascBoxRec;
RASC_STATIC_ASSERT(sizeof(RascBoxRec) == 48, "RascBoxRec size");
RASC_STATIC_ASSERT(offsetof(RascBoxRec, center) == 0, "RascBoxRec.center");
RASC_STATIC_ASSERT(offsetof(RascBoxRec, half) == 12, "RascBoxRec.half");
RASC_STATIC_ASSERT(offsetof(RascBoxRec, yaw) == 24, "RascBoxRec.yaw");
RASC_STATIC_ASSERT(offsetof(RascBoxRec, cat) == 28, "RascBoxRec.cat");
RASC_STATIC_ASSERT(offsetof(RascBoxRec, room) == 30, "RascBoxRec.room");
RASC_STATIC_ASSERT(offsetof(RascBoxRec, flags) == 32, "RascBoxRec.flags");
RASC_STATIC_ASSERT(offsetof(RascBoxRec, obj) == 36, "RascBoxRec.obj");
RASC_STATIC_ASSERT(offsetof(RascBoxRec, zmin) == 40, "RascBoxRec.zmin");
RASC_STATIC_ASSERT(offsetof(RascBoxRec, zmax) == 44, "RascBoxRec.zmax");

/* door-like scene object (category contains 'door') */
typedef struct RascDoorRec {
    uint32_t obj; /* ObjRec index */
    uint16_t room_a; /* RoomRec index or 0xFFFF */
    uint16_t room_b; /* RoomRec index or 0xFFFF */
    uint16_t kind; /* 0 door, 1 sliding_door, 2 garage_door, 3 elevator_door, 4 other */
    uint16_t n_joints;
    uint32_t joint_off; /* JOINTS pool */
    float center[3]; /* world bbox center */
    float half[3]; /* object-frame half extents */
    float yaw;
    uint32_t reserved; /* 0 */
} RascDoorRec;
RASC_STATIC_ASSERT(sizeof(RascDoorRec) == 48, "RascDoorRec size");
RASC_STATIC_ASSERT(offsetof(RascDoorRec, obj) == 0, "RascDoorRec.obj");
RASC_STATIC_ASSERT(offsetof(RascDoorRec, room_a) == 4, "RascDoorRec.room_a");
RASC_STATIC_ASSERT(offsetof(RascDoorRec, room_b) == 6, "RascDoorRec.room_b");
RASC_STATIC_ASSERT(offsetof(RascDoorRec, kind) == 8, "RascDoorRec.kind");
RASC_STATIC_ASSERT(offsetof(RascDoorRec, n_joints) == 10, "RascDoorRec.n_joints");
RASC_STATIC_ASSERT(offsetof(RascDoorRec, joint_off) == 12, "RascDoorRec.joint_off");
RASC_STATIC_ASSERT(offsetof(RascDoorRec, center) == 16, "RascDoorRec.center");
RASC_STATIC_ASSERT(offsetof(RascDoorRec, half) == 28, "RascDoorRec.half");
RASC_STATIC_ASSERT(offsetof(RascDoorRec, yaw) == 40, "RascDoorRec.yaw");
RASC_STATIC_ASSERT(offsetof(RascDoorRec, reserved) == 44, "RascDoorRec.reserved");

/* BEHAVIOR task (problem0.bddl) whose scene is this file */
typedef struct RascTaskRec {
    uint32_t name; /* string offset: task name */
    uint16_t task_index; /* 0..99 (metadata/task.jsonl) */
    uint16_t n_obj; /* task objects (BDDL :objects, incl. agent and systems) */
    uint16_t n_init; /* init literals */
    uint16_t n_goal; /* goal literals (all or-branches) */
    uint16_t n_var; /* goal variables */
    uint16_t n_cand; /* candidate entries */
    uint16_t n_removed; /* scene objects the task template does not load */
    uint16_t n_or_groups; /* or groups */
    uint16_t n_doc_lits; /* goal literals counted like the doc (first or-branch) */
    uint16_t n_not_open; /* doc 1.4 'initially true' count: goal 'not open' literals (doc rule) */
    uint16_t n_init_true; /* doc literals already true under the BDDL :init (closed world) */
    uint16_t skills; /* RASC_SK_* bits (doc 1.3 skill letters) */
    uint32_t obj_off; /* TaskObjRec index */
    uint32_t init_off; /* LitRec index of init literals */
    uint32_t goal_off; /* LitRec index of goal literals */
    uint32_t var_off; /* VarRec index */
    uint32_t cand_off; /* CANDS (u16) index */
    uint32_t removed_off; /* REMOVED (u16 ObjRec indices) index */
    uint32_t inst_off; /* InstRec index */
    uint32_t n_inst; /* instances (train then public) */
    uint32_t n_train;
    uint32_t n_public;
    float human_s; /* mean human demo length (s) = task.jsonl length / 30 */
    float limit_s; /* evaluation time limit (s) = human_s * 1.5 */
    float dist_m; /* human demo base travel (m) */
    float q_strict; /* doc 1.5 q upper bound, strict */
    float q_loose; /* doc 1.5 q upper bound, loose */
    uint64_t rooms_mask; /* bit i = RoomRec i is in B100_task_misc.csv 'Rooms to include' */
} RascTaskRec;
RASC_STATIC_ASSERT(sizeof(RascTaskRec) == 96, "RascTaskRec size");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, name) == 0, "RascTaskRec.name");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, task_index) == 4, "RascTaskRec.task_index");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, n_obj) == 6, "RascTaskRec.n_obj");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, n_init) == 8, "RascTaskRec.n_init");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, n_goal) == 10, "RascTaskRec.n_goal");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, n_var) == 12, "RascTaskRec.n_var");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, n_cand) == 14, "RascTaskRec.n_cand");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, n_removed) == 16, "RascTaskRec.n_removed");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, n_or_groups) == 18, "RascTaskRec.n_or_groups");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, n_doc_lits) == 20, "RascTaskRec.n_doc_lits");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, n_not_open) == 22, "RascTaskRec.n_not_open");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, n_init_true) == 24, "RascTaskRec.n_init_true");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, skills) == 26, "RascTaskRec.skills");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, obj_off) == 28, "RascTaskRec.obj_off");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, init_off) == 32, "RascTaskRec.init_off");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, goal_off) == 36, "RascTaskRec.goal_off");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, var_off) == 40, "RascTaskRec.var_off");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, cand_off) == 44, "RascTaskRec.cand_off");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, removed_off) == 48, "RascTaskRec.removed_off");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, inst_off) == 52, "RascTaskRec.inst_off");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, n_inst) == 56, "RascTaskRec.n_inst");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, n_train) == 60, "RascTaskRec.n_train");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, n_public) == 64, "RascTaskRec.n_public");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, human_s) == 68, "RascTaskRec.human_s");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, limit_s) == 72, "RascTaskRec.limit_s");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, dist_m) == 76, "RascTaskRec.dist_m");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, q_strict) == 80, "RascTaskRec.q_strict");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, q_loose) == 84, "RascTaskRec.q_loose");
RASC_STATIC_ASSERT(offsetof(RascTaskRec, rooms_mask) == 88, "RascTaskRec.rooms_mask");

/* task object: BDDL instance joined with the task template */
typedef struct RascTaskObjRec {
    uint32_t inst; /* string offset: BDDL instance, e.g. 'jar__of__honey.n.01_1' */
    uint32_t syn; /* string offset: synset */
    uint32_t og_name; /* string offset: OmniGibson name (inst_to_name), '' if unmapped */
    uint16_t cat; /* CatRec index or 0xFFFF (agent / system / unmapped) */
    uint16_t n_joints; /* joint_pos length in the template state */
    uint32_t flags; /* RASC_F_* */
    int32_t scene_obj; /* ObjRec index if this is a scene object, else -1 */
    float scale[3];
    float half[3]; /* scale * bbox_size / 2 (object frame); 0 if no bbox */
    float offset[3]; /* scale * base_link_offset (object frame) */
    float mass; /* category average mass (kg) or NaN */
    float pos[3]; /* template (instance 0) root position */
    float quat[4]; /* template root orientation (x, y, z, w) */
} RascTaskObjRec;
RASC_STATIC_ASSERT(sizeof(RascTaskObjRec) == 92, "RascTaskObjRec size");
RASC_STATIC_ASSERT(offsetof(RascTaskObjRec, inst) == 0, "RascTaskObjRec.inst");
RASC_STATIC_ASSERT(offsetof(RascTaskObjRec, syn) == 4, "RascTaskObjRec.syn");
RASC_STATIC_ASSERT(offsetof(RascTaskObjRec, og_name) == 8, "RascTaskObjRec.og_name");
RASC_STATIC_ASSERT(offsetof(RascTaskObjRec, cat) == 12, "RascTaskObjRec.cat");
RASC_STATIC_ASSERT(offsetof(RascTaskObjRec, n_joints) == 14, "RascTaskObjRec.n_joints");
RASC_STATIC_ASSERT(offsetof(RascTaskObjRec, flags) == 16, "RascTaskObjRec.flags");
RASC_STATIC_ASSERT(offsetof(RascTaskObjRec, scene_obj) == 20, "RascTaskObjRec.scene_obj");
RASC_STATIC_ASSERT(offsetof(RascTaskObjRec, scale) == 24, "RascTaskObjRec.scale");
RASC_STATIC_ASSERT(offsetof(RascTaskObjRec, half) == 36, "RascTaskObjRec.half");
RASC_STATIC_ASSERT(offsetof(RascTaskObjRec, offset) == 48, "RascTaskObjRec.offset");
RASC_STATIC_ASSERT(offsetof(RascTaskObjRec, mass) == 60, "RascTaskObjRec.mass");
RASC_STATIC_ASSERT(offsetof(RascTaskObjRec, pos) == 64, "RascTaskObjRec.pos");
RASC_STATIC_ASSERT(offsetof(RascTaskObjRec, quat) == 76, "RascTaskObjRec.quat");

/* literal (init or goal) */
typedef struct RascLitRec {
    uint8_t pred; /* RASC_P_* */
    uint8_t neg; /* 1 = negated */
    uint8_t nargs; /* 1 or 2 */
    uint8_t flags; /* RASC_L_* */
    uint16_t or_group; /* or group (task-local) or 0xFFFF */
    uint16_t or_branch; /* branch within the group */
    uint16_t arg[2]; /* RASC_ARG_VAR bit -> VarRec index; RASC_ARG_ROOM bit -> room category; else TaskObjRec index (task-local) */
    uint32_t reserved; /* 0 */
} RascLitRec;
RASC_STATIC_ASSERT(sizeof(RascLitRec) == 16, "RascLitRec size");
RASC_STATIC_ASSERT(offsetof(RascLitRec, pred) == 0, "RascLitRec.pred");
RASC_STATIC_ASSERT(offsetof(RascLitRec, neg) == 1, "RascLitRec.neg");
RASC_STATIC_ASSERT(offsetof(RascLitRec, nargs) == 2, "RascLitRec.nargs");
RASC_STATIC_ASSERT(offsetof(RascLitRec, flags) == 3, "RascLitRec.flags");
RASC_STATIC_ASSERT(offsetof(RascLitRec, or_group) == 4, "RascLitRec.or_group");
RASC_STATIC_ASSERT(offsetof(RascLitRec, or_branch) == 6, "RascLitRec.or_branch");
RASC_STATIC_ASSERT(offsetof(RascLitRec, arg) == 8, "RascLitRec.arg");
RASC_STATIC_ASSERT(offsetof(RascLitRec, reserved) == 12, "RascLitRec.reserved");

/* goal variable: binds to one of its candidates */
typedef struct RascVarRec {
    uint8_t kind; /* 1 exists, 2 forn, 3 forpairs */
    uint8_t reserved; /* 0 */
    uint16_t group; /* distinct group (forn/forpairs: members bind to different objects) or 0xFFFF */
    uint16_t cand_off; /* task-local CANDS index */
    uint16_t cand_n;
} RascVarRec;
RASC_STATIC_ASSERT(sizeof(RascVarRec) == 8, "RascVarRec size");
RASC_STATIC_ASSERT(offsetof(RascVarRec, kind) == 0, "RascVarRec.kind");
RASC_STATIC_ASSERT(offsetof(RascVarRec, reserved) == 1, "RascVarRec.reserved");
RASC_STATIC_ASSERT(offsetof(RascVarRec, group) == 2, "RascVarRec.group");
RASC_STATIC_ASSERT(offsetof(RascVarRec, cand_off) == 4, "RascVarRec.cand_off");
RASC_STATIC_ASSERT(offsetof(RascVarRec, cand_n) == 6, "RascVarRec.cand_n");

/* task instance: robot start + task object states */
typedef struct RascInstRec {
    uint16_t task; /* TaskRec index in this file */
    uint16_t split; /* 0 train (scenes/, ids 1..300 for tasks 50-99, 0..299 for tasks 0-49), 1 public eval (scene_test/public/, ids 301..320) */
    uint32_t inst_id; /* instance id from the file name */
    uint32_t pose_off; /* PoseRec index; n_pose = task n_obj, same order (agent / systems get src 0) */
    uint16_t n_pose;
    uint16_t flags; /* bit 0: robot pose is the R1Pro-specific one (2025 train files have no generic pose) */
    float robot_pos[3]; /* robot_poses.robot[0].position */
    float robot_quat[4]; /* robot_poses.robot[0].orientation (x, y, z, w) */
    float robot_yaw;
} RascInstRec;
RASC_STATIC_ASSERT(sizeof(RascInstRec) == 48, "RascInstRec size");
RASC_STATIC_ASSERT(offsetof(RascInstRec, task) == 0, "RascInstRec.task");
RASC_STATIC_ASSERT(offsetof(RascInstRec, split) == 2, "RascInstRec.split");
RASC_STATIC_ASSERT(offsetof(RascInstRec, inst_id) == 4, "RascInstRec.inst_id");
RASC_STATIC_ASSERT(offsetof(RascInstRec, pose_off) == 8, "RascInstRec.pose_off");
RASC_STATIC_ASSERT(offsetof(RascInstRec, n_pose) == 12, "RascInstRec.n_pose");
RASC_STATIC_ASSERT(offsetof(RascInstRec, flags) == 14, "RascInstRec.flags");
RASC_STATIC_ASSERT(offsetof(RascInstRec, robot_pos) == 16, "RascInstRec.robot_pos");
RASC_STATIC_ASSERT(offsetof(RascInstRec, robot_quat) == 28, "RascInstRec.robot_quat");
RASC_STATIC_ASSERT(offsetof(RascInstRec, robot_yaw) == 44, "RascInstRec.robot_yaw");

/* task object state in one instance */
typedef struct RascPoseRec {
    float pos[3]; /* root link position */
    float quat[4]; /* (x, y, z, w) */
    uint32_t joint_off; /* JOINTS pool */
    uint16_t n_joints;
    uint16_t src; /* 0 none (agent/system), 1 instance file, 2 scene file (object absent from the instance), 3 template (known dataset defect) */
} RascPoseRec;
RASC_STATIC_ASSERT(sizeof(RascPoseRec) == 36, "RascPoseRec size");
RASC_STATIC_ASSERT(offsetof(RascPoseRec, pos) == 0, "RascPoseRec.pos");
RASC_STATIC_ASSERT(offsetof(RascPoseRec, quat) == 12, "RascPoseRec.quat");
RASC_STATIC_ASSERT(offsetof(RascPoseRec, joint_off) == 28, "RascPoseRec.joint_off");
RASC_STATIC_ASSERT(offsetof(RascPoseRec, n_joints) == 32, "RascPoseRec.n_joints");
RASC_STATIC_ASSERT(offsetof(RascPoseRec, src) == 34, "RascPoseRec.src");

/* pick-and-place limits used for PICKS/PLACES (2 records: [0] outer = inclusion, [1] inner = flag bit 0) */
typedef struct RascLimitsRec {
    float pick_z; /* max bottom height (m) of a graspable object (top-down grasp from the LIMO base) */
    float place_top; /* max top height (m) of an ontop support */
    float inside_margin; /* an open container may be this much higher than place_top (m) */
    float max_mass; /* max mass (kg; category average) */
    float max_w; /* max of the smaller horizontal box side (m) = gripper opening */
    float min_side; /* min smaller horizontal side (m) of an ontop support */
    float min_top; /* min top height (m) of an ontop support (floor is its own kind) */
    float reach; /* max xy distance (m) from a free base cell center to the object's box footprint */
} RascLimitsRec;
RASC_STATIC_ASSERT(sizeof(RascLimitsRec) == 32, "RascLimitsRec size");
RASC_STATIC_ASSERT(offsetof(RascLimitsRec, pick_z) == 0, "RascLimitsRec.pick_z");
RASC_STATIC_ASSERT(offsetof(RascLimitsRec, place_top) == 4, "RascLimitsRec.place_top");
RASC_STATIC_ASSERT(offsetof(RascLimitsRec, inside_margin) == 8, "RascLimitsRec.inside_margin");
RASC_STATIC_ASSERT(offsetof(RascLimitsRec, max_mass) == 12, "RascLimitsRec.max_mass");
RASC_STATIC_ASSERT(offsetof(RascLimitsRec, max_w) == 16, "RascLimitsRec.max_w");
RASC_STATIC_ASSERT(offsetof(RascLimitsRec, min_side) == 20, "RascLimitsRec.min_side");
RASC_STATIC_ASSERT(offsetof(RascLimitsRec, min_top) == 24, "RascLimitsRec.min_top");
RASC_STATIC_ASSERT(offsetof(RascLimitsRec, reach) == 28, "RascLimitsRec.reach");

/* graspable object candidate */
typedef struct RascPickRec {
    uint32_t obj; /* ObjRec index, or RASC_PNP_TASKOBJ | TaskObjRec index (instance level) */
    uint32_t inst; /* InstRec index, 0xffffffff = scene level (static) */
    float center[3]; /* world box center */
    float z0; /* world AABB bottom */
    float top; /* world AABB top */
    float min_w; /* smaller horizontal side of the object box (m) */
    float mass; /* category average mass (kg) or NaN */
    float yaw;
    uint16_t room; /* RoomRec index at the center or 0xffff */
    uint16_t comp; /* TRAV connected component of its approach cells (largest), 0xffff = none */
    uint32_t n_approach; /* TRAV-free cells within reach of the footprint */
    uint32_t src_place; /* PlaceRec index it rests on / in (same level or scene level), 0xffffffff = unknown */
    uint32_t flags; /* RASC_PK_* */
    uint32_t reserved[2]; /* 0 */
} RascPickRec;
RASC_STATIC_ASSERT(sizeof(RascPickRec) == 64, "RascPickRec size");
RASC_STATIC_ASSERT(offsetof(RascPickRec, obj) == 0, "RascPickRec.obj");
RASC_STATIC_ASSERT(offsetof(RascPickRec, inst) == 4, "RascPickRec.inst");
RASC_STATIC_ASSERT(offsetof(RascPickRec, center) == 8, "RascPickRec.center");
RASC_STATIC_ASSERT(offsetof(RascPickRec, z0) == 20, "RascPickRec.z0");
RASC_STATIC_ASSERT(offsetof(RascPickRec, top) == 24, "RascPickRec.top");
RASC_STATIC_ASSERT(offsetof(RascPickRec, min_w) == 28, "RascPickRec.min_w");
RASC_STATIC_ASSERT(offsetof(RascPickRec, mass) == 32, "RascPickRec.mass");
RASC_STATIC_ASSERT(offsetof(RascPickRec, yaw) == 36, "RascPickRec.yaw");
RASC_STATIC_ASSERT(offsetof(RascPickRec, room) == 40, "RascPickRec.room");
RASC_STATIC_ASSERT(offsetof(RascPickRec, comp) == 42, "RascPickRec.comp");
RASC_STATIC_ASSERT(offsetof(RascPickRec, n_approach) == 44, "RascPickRec.n_approach");
RASC_STATIC_ASSERT(offsetof(RascPickRec, src_place) == 48, "RascPickRec.src_place");
RASC_STATIC_ASSERT(offsetof(RascPickRec, flags) == 52, "RascPickRec.flags");
RASC_STATIC_ASSERT(offsetof(RascPickRec, reserved) == 56, "RascPickRec.reserved");

/* support candidate (ontop surface, open container, or a room's floor) */
typedef struct RascPlaceRec {
    uint32_t obj; /* ObjRec index, RASC_PNP_TASKOBJ | TaskObjRec index, or 0xffffffff for a floor */
    uint32_t inst; /* InstRec index, 0xffffffff = scene level */
    uint16_t kind; /* 1 ontop surface, 2 inside open container, 3 floor of a room */
    uint16_t room; /* RoomRec index */
    float center[3]; /* world box center (floor: room centroid, z 0) */
    float half[2]; /* object-frame half extents xy (floor: room bbox half) */
    float yaw;
    float top; /* world AABB top (floor: 0) */
    uint32_t n_approach; /* TRAV-free cells within reach (floor: free cells of the room) */
    uint16_t comp; /* TRAV component (largest among approach cells), 0xffff = none */
    uint16_t flags; /* bit 0: also within the inner (strict) limits */
} RascPlaceRec;
RASC_STATIC_ASSERT(sizeof(RascPlaceRec) == 48, "RascPlaceRec size");
RASC_STATIC_ASSERT(offsetof(RascPlaceRec, obj) == 0, "RascPlaceRec.obj");
RASC_STATIC_ASSERT(offsetof(RascPlaceRec, inst) == 4, "RascPlaceRec.inst");
RASC_STATIC_ASSERT(offsetof(RascPlaceRec, kind) == 8, "RascPlaceRec.kind");
RASC_STATIC_ASSERT(offsetof(RascPlaceRec, room) == 10, "RascPlaceRec.room");
RASC_STATIC_ASSERT(offsetof(RascPlaceRec, center) == 12, "RascPlaceRec.center");
RASC_STATIC_ASSERT(offsetof(RascPlaceRec, half) == 24, "RascPlaceRec.half");
RASC_STATIC_ASSERT(offsetof(RascPlaceRec, yaw) == 32, "RascPlaceRec.yaw");
RASC_STATIC_ASSERT(offsetof(RascPlaceRec, top) == 36, "RascPlaceRec.top");
RASC_STATIC_ASSERT(offsetof(RascPlaceRec, n_approach) == 40, "RascPlaceRec.n_approach");
RASC_STATIC_ASSERT(offsetof(RascPlaceRec, comp) == 44, "RascPlaceRec.comp");
RASC_STATIC_ASSERT(offsetof(RascPlaceRec, flags) == 46, "RascPlaceRec.flags");

/* pick-and-place candidate: object, source support, target support */
typedef struct RascPairRec {
    uint32_t pick; /* PickRec index */
    uint32_t src; /* PlaceRec index of the source support (= pick.src_place) */
    uint32_t dst; /* PlaceRec index of the target support */
    uint8_t rel; /* RASC_P_ONTOP or RASC_P_INSIDE */
    uint8_t reachable; /* bit 0: pick and target approach cells share a TRAV component; bit 1: both within inner limits; bit 2: instance robot start in that component */
    uint16_t room_pick; /* RoomRec index of the object */
    uint16_t room_dst; /* RoomRec index of the target */
    uint16_t reserved; /* 0 */
    float dist; /* xy distance object -> target (m) */
} RascPairRec;
RASC_STATIC_ASSERT(sizeof(RascPairRec) == 24, "RascPairRec size");
RASC_STATIC_ASSERT(offsetof(RascPairRec, pick) == 0, "RascPairRec.pick");
RASC_STATIC_ASSERT(offsetof(RascPairRec, src) == 4, "RascPairRec.src");
RASC_STATIC_ASSERT(offsetof(RascPairRec, dst) == 8, "RascPairRec.dst");
RASC_STATIC_ASSERT(offsetof(RascPairRec, rel) == 12, "RascPairRec.rel");
RASC_STATIC_ASSERT(offsetof(RascPairRec, reachable) == 13, "RascPairRec.reachable");
RASC_STATIC_ASSERT(offsetof(RascPairRec, room_pick) == 14, "RascPairRec.room_pick");
RASC_STATIC_ASSERT(offsetof(RascPairRec, room_dst) == 16, "RascPairRec.room_dst");
RASC_STATIC_ASSERT(offsetof(RascPairRec, reserved) == 18, "RascPairRec.reserved");
RASC_STATIC_ASSERT(offsetof(RascPairRec, dist) == 20, "RascPairRec.dist");

/* per-instance ranges into PICKS/PLACES/PAIRS (n_inst + 1 entries; the last = scene level) */
typedef struct RascPnpRange {
    uint32_t pick_off;
    uint32_t place_off;
    uint32_t pair_off;
    uint16_t n_pick;
    uint16_t n_place;
    uint32_t n_pair;
    uint16_t robot_comp; /* TRAV component of the robot start cell (0xffff none / scene level) */
    uint16_t reserved; /* 0 */
} RascPnpRange;
RASC_STATIC_ASSERT(sizeof(RascPnpRange) == 24, "RascPnpRange size");
RASC_STATIC_ASSERT(offsetof(RascPnpRange, pick_off) == 0, "RascPnpRange.pick_off");
RASC_STATIC_ASSERT(offsetof(RascPnpRange, place_off) == 4, "RascPnpRange.place_off");
RASC_STATIC_ASSERT(offsetof(RascPnpRange, pair_off) == 8, "RascPnpRange.pair_off");
RASC_STATIC_ASSERT(offsetof(RascPnpRange, n_pick) == 12, "RascPnpRange.n_pick");
RASC_STATIC_ASSERT(offsetof(RascPnpRange, n_place) == 14, "RascPnpRange.n_place");
RASC_STATIC_ASSERT(offsetof(RascPnpRange, n_pair) == 16, "RascPnpRange.n_pair");
RASC_STATIC_ASSERT(offsetof(RascPnpRange, robot_comp) == 20, "RascPnpRange.robot_comp");
RASC_STATIC_ASSERT(offsetof(RascPnpRange, reserved) == 22, "RascPnpRange.reserved");

enum {
    RASC_SEC_STRINGS = 0,
    RASC_SEC_CATS = 1,
    RASC_SEC_ROOMS = 2,
    RASC_SEC_OBJS = 3,
    RASC_SEC_BOXES = 4,
    RASC_SEC_DOORS = 5,
    RASC_SEC_JOINTS = 6,
    RASC_SEC_ROOM_GRID = 7,
    RASC_SEC_TRAV = 8,
    RASC_SEC_TRAV_NO_OBJ = 9,
    RASC_SEC_TRAV_NO_DOOR = 10,
    RASC_SEC_TRAV_OPEN_DOOR = 11,
    RASC_SEC_TASKS = 12,
    RASC_SEC_TASK_OBJS = 13,
    RASC_SEC_LITS = 14,
    RASC_SEC_VARS = 15,
    RASC_SEC_CANDS = 16,
    RASC_SEC_REMOVED = 17,
    RASC_SEC_INSTS = 18,
    RASC_SEC_POSES = 19,
    RASC_SEC_IN_ROOMS = 20,
    RASC_SEC_LIMITS = 21,
    RASC_SEC_PICKS = 22,
    RASC_SEC_PLACES = 23,
    RASC_SEC_PAIRS = 24,
    RASC_SEC_PNP_RANGES = 25,
    RASC_SEC_RES26 = 26,
    RASC_SEC_RES27 = 27,
    RASC_NSEC = 28
};

enum {
    RASC_F_WALL = 0x1u, /* category walls */
    RASC_F_FLOOR = 0x2u, /* category floors */
    RASC_F_CEILING = 0x4u, /* category ceilings */
    RASC_F_DOOR = 0x8u, /* category contains 'door' */
    RASC_F_WINDOW = 0x10u, /* category contains 'window' */
    RASC_F_STAIRS = 0x20u, /* category contains 'stair' */
    RASC_F_FIXED_BASE = 0x40u, /* args.fixed_base */
    RASC_F_ARTICULATED = 0x80u, /* state has joint_pos */
    RASC_F_OPENABLE = 0x100u, /* metadata openable_joint_ids or an 'openable' link tag */
    RASC_F_TOGGLEABLE = 0x200u, /* metadata meta_links has togglebutton */
    RASC_F_VISUAL_ONLY = 0x400u, /* args.visual_only */
    RASC_F_CARPET = 0x800u, /* category carpet/rug (flat) */
    RASC_F_HEATSOURCE = 0x1000u, /* meta link heatsource */
    RASC_F_FLUID_SOURCE = 0x2000u, /* meta link fluidsource */
    RASC_F_FLUID_SINK = 0x4000u, /* meta link fluidsink */
    RASC_F_ATTACHMENT = 0x8000u, /* meta link attachment */
    RASC_F_TILTED = 0x10000u, /* object z axis more than 5 deg from world z (yaw-only box is approximate) */
    RASC_F_HAS_BBOX = 0x20000u, /* metadata.json found (bbox valid) */
    RASC_F_SYSTEM = 0x40000u, /* task object is a particle/fluid system (no rigid body) */
    RASC_F_AGENT = 0x80000u, /* task object is the robot */
    RASC_F_SCENE_OBJ = 0x100000u, /* task object is a scene object (scene_obj >= 0) */
    RASC_F_WILDCARD = 0x200000u, /* BDDL wildcard instance (name ends with _*) */
    RASC_F_UNMAPPED = 0x400000u, /* not in the template inst_to_name */
    RASC_F_FUTURE = 0x800000u, /* BDDL init (future x): created during the task */
    RASC_F_LIGHT = 0x1000000u, /* meta link lights */
};

enum {
    RASC_P_INROOM = 1,
    RASC_P_ONTOP = 2,
    RASC_P_INSIDE = 3,
    RASC_P_NEXTTO = 4,
    RASC_P_UNDER = 5,
    RASC_P_TOUCHING = 6,
    RASC_P_ATTACHED = 7,
    RASC_P_OPEN = 8,
    RASC_P_TOGGLED_ON = 9,
    RASC_P_COOKED = 10,
    RASC_P_FROZEN = 11,
    RASC_P_HOT = 12,
    RASC_P_ON_FIRE = 13,
    RASC_P_COVERED = 14,
    RASC_P_FILLED = 15,
    RASC_P_CONTAINS = 16,
    RASC_P_SATURATED = 17,
    RASC_P_INSOURCE = 18,
    RASC_P_REAL = 19,
    RASC_P_FUTURE = 20,
    RASC_P_OVERLAID = 21,
    RASC_P_DRAPED = 22,
    RASC_P_FOLDED = 23,
    RASC_P_UNFOLDED = 24,
    RASC_P_BROKEN = 25,
    RASC_NPRED = 26
};

enum {
    RASC_L_DOC = 1, /* counted by the doc rule (all or-tags on branch 0) */
    RASC_L_INIT_TRUE = 2, /* goal literal already true under the BDDL :init (closed world; candidates: any) */
    RASC_L_IN_OR = 4, /* inside an or-branch */
};

enum {
    RASC_PK_INNER = 1, /* also within the inner (strict) limits */
    RASC_PK_MASS_UNKNOWN = 2, /* category has no average mass (mass limit not applied) */
    RASC_PK_SCENE_OBJ = 4, /* instance-level entry of a scene object in the task scope (overrides the scene-level one) */
    RASC_PK_IN_CLOSED = 8, /* BDDL init puts it inside a closed articulated container */
};

enum {
    RASC_SK_MULTI_ROOM = 1 << 0, /* doc letter M */
    RASC_SK_PICK = 1 << 1, /* doc letter P */
    RASC_SK_OPEN = 1 << 2, /* doc letter O */
    RASC_SK_TOGGLE = 1 << 3, /* doc letter T */
    RASC_SK_HEAT = 1 << 4, /* doc letter H */
    RASC_SK_SLICE = 1 << 5, /* doc letter S */
    RASC_SK_CLEAN = 1 << 6, /* doc letter C */
    RASC_SK_FILL = 1 << 7, /* doc letter F */
    RASC_SK_ATTACH = 1 << 8, /* doc letter A */
    RASC_SK_HEAVY = 1 << 9, /* doc letter W */
};

#define RASC_ARG_VAR 0x8000u
#define RASC_ARG_ROOM 0x4000u
#define RASC_NONE16 0xffffu
#define RASC_NONE32 0xffffffffu
#define RASC_PNP_TASKOBJ 0x80000000u

static const char* const rasc_pred_names[] = {"", "inroom", "ontop", "inside", "nextto", "under", "touching", "attached", "open", "toggled_on", "cooked", "frozen", "hot", "on_fire", "covered", "filled", "contains", "saturated", "insource", "real", "future", "overlaid", "draped", "folded", "unfolded", "broken", };
static const char* const rasc_sec_names[] = {"STRINGS", "CATS", "ROOMS", "OBJS", "BOXES", "DOORS", "JOINTS", "ROOM_GRID", "TRAV", "TRAV_NO_OBJ", "TRAV_NO_DOOR", "TRAV_OPEN_DOOR", "TASKS", "TASK_OBJS", "LITS", "VARS", "CANDS", "REMOVED", "INSTS", "POSES", "IN_ROOMS", "LIMITS", "PICKS", "PLACES", "PAIRS", "PNP_RANGES", "RES26", "RES27", };
