// GENERATED by training/embed/vla_vocab_gen.py from training/data/vla_v1 (manifest sha a417f8052138844b, 2026-10-04) — do not edit.
// VLA_INPUT 3절 이름 뜻 벡터·이름 확신도의 장치 표(지도 토큰용, CPU·GPU 같은 값). 벡터 자체(name128.f16·app128.f16)는 런타임 파일로 읽는다.
//   sim_name(cls)  : gmap::Cls → name128 행 (cup, box, chair, table, cabinet, trash can)
//   sim_hyper(cls) : 확신이 낮을 때 쓰는 상위어 행 (tableware, container, furniture, furniture, furniture, container)
//   conf1(app, cls): cos(app128[app], name128[sim_name(cls)]),  conf2 = conf1 − (이름 어휘에서 cls 동의어 묶음 밖 최대 코사인)
//                    app = 0..5 gmap::Cls(그 물체의 생김새), 6 = 유령(가짜 검출 — 바닥·벽 조각)
//   kConfLow       : conf2 < kConfLow 이면 지도 토큰 이름 = sim_hyper(cls)
#pragma once
#include <cstdint>

namespace vlav {

constexpr int N_NAME = 584;
constexpr int N_APP = 7;
constexpr int DIM = 128;
constexpr float kConfLow = -0x1.47ae140000000p-4f;

#define VLAV_SIM_NAME {0, 4, 8, 11, 15, 19}
#define VLAV_SIM_HYPER {447, 147, 448, 448, 448, 147}
#define VLAV_CONF1 {{0x1.0fe7200000000p-4f, 0x1.7593fe0000000p-3f, 0x1.ad9cb80000000p-4f, 0x1.cef9100000000p-4f, 0x1.8773600000000p-4f, 0x1.3e48d20000000p-3f}, {0x1.1ae33c0000000p-4f, 0x1.3b61a60000000p-3f, 0x1.e2f1480000000p-4f, 0x1.a1f3c20000000p-4f, 0x1.5afa780000000p-4f, 0x1.781a3c0000000p-3f}, {0x1.7c8db60000000p-4f, 0x1.4739440000000p-3f, 0x1.c081f40000000p-4f, 0x1.aba78e0000000p-4f, 0x1.3723c80000000p-3f, 0x1.8f4df00000000p-3f}, {0x1.3c37d20000000p-5f, 0x1.30e4ba0000000p-3f, 0x1.ae15a00000000p-4f, 0x1.bfefd00000000p-4f, 0x1.773c680000000p-4f, 0x1.41dd0e0000000p-3f}, {0x1.9554d00000000p-4f, 0x1.eabab40000000p-4f, 0x1.a780360000000p-4f, 0x1.42e0020000000p-4f, 0x1.95c63e0000000p-4f, 0x1.af3b140000000p-3f}, {0x1.5b95600000000p-4f, 0x1.4b269c0000000p-3f, 0x1.d6bab60000000p-4f, 0x1.9b56120000000p-4f, 0x1.8af3ec0000000p-4f, 0x1.a9715e0000000p-3f}, {-0x1.45f68c0000000p-6f, 0x1.4e5cc40000000p-7f, 0x1.89d44c0000000p-5f, 0x1.b39d8e0000000p-5f, 0x1.3877340000000p-4f, 0x1.0de2180000000p-5f}}
#define VLAV_CONF2 {{-0x1.f6081c0000000p-4f, -0x1.ac74000000000p-8f, -0x1.5852840000000p-4f, -0x1.36f62c0000000p-4f, -0x1.7e7bdc0000000p-4f, -0x1.12bb300000000p-5f}, {-0x1.3126dc0000000p-3f, -0x1.066da80000000p-4f, -0x1.9a3fac0000000p-4f, -0x1.db3d320000000p-4f, -0x1.111b3e0000000p-3f, 0x1.1e68000000000p-10f}, {-0x1.095cdc0000000p-3f, -0x1.00d4e80000000p-4f, -0x1.cec57c0000000p-4f, -0x1.e39fe20000000p-4f, -0x1.20ffe00000000p-4f, 0x1.f720000000000p-12f}, {-0x1.22b6d40000000p-3f, -0x1.0380380000000p-5f, -0x1.3573f00000000p-4f, -0x1.2399c00000000p-4f, -0x1.6c4d280000000p-4f, 0x1.3661000000000p-9f}, {-0x1.17538e0000000p-3f, -0x1.d941380000000p-4f, -0x1.0e3ddc0000000p-3f, -0x1.408df40000000p-3f, -0x1.171ad80000000p-3f, 0x1.3054800000000p-8f}, {-0x1.3607f20000000p-3f, -0x1.31580c0000000p-4f, -0x1.f0ea8e0000000p-4f, -0x1.1627980000000p-3f, -0x1.1e58ac0000000p-3f, 0x1.90d3400000000p-6f}, {-0x1.6a7ca80000000p-3f, -0x1.2cd80a0000000p-3f, -0x1.be91860000000p-4f, -0x1.a9ace40000000p-4f, -0x1.4b04780000000p-4f, -0x1.fc8aa00000000p-4f}}

constexpr int16_t kSimName[6] = VLAV_SIM_NAME;
constexpr int16_t kSimHyper[6] = VLAV_SIM_HYPER;
constexpr float kConf1[7][6] = VLAV_CONF1;
constexpr float kConf2[7][6] = VLAV_CONF2;
#ifdef __CUDACC__
static __constant__ int16_t kSimNameDev[6] = VLAV_SIM_NAME;
static __constant__ int16_t kSimHyperDev[6] = VLAV_SIM_HYPER;
static __constant__ float kConf1Dev[7][6] = VLAV_CONF1;
static __constant__ float kConf2Dev[7][6] = VLAV_CONF2;
#define VLAV_FN __host__ __device__ __forceinline__
#else
#define VLAV_FN inline
#endif

VLAV_FN int16_t sim_name(int cls) {
#ifdef __CUDA_ARCH__
  return kSimNameDev[cls];
#else
  return kSimName[cls];
#endif
}
VLAV_FN int16_t sim_hyper(int cls) {
#ifdef __CUDA_ARCH__
  return kSimHyperDev[cls];
#else
  return kSimHyper[cls];
#endif
}
VLAV_FN float conf1(int app, int cls) {
#ifdef __CUDA_ARCH__
  return kConf1Dev[app][cls];
#else
  return kConf1[app][cls];
#endif
}
VLAV_FN float conf2(int app, int cls) {
#ifdef __CUDA_ARCH__
  return kConf2Dev[app][cls];
#else
  return kConf2[app][cls];
#endif
}

#undef VLAV_FN
#undef VLAV_SIM_NAME
#undef VLAV_SIM_HYPER
#undef VLAV_CONF1
#undef VLAV_CONF2

}  // namespace vlav
