"""Generate training/RL/map/include/vla_vocab.h (+ refresh training/data/vla_v1/manifest.json) from the VLA tables. OFFLINE, numpy only.

  python3 training/embed/vla_vocab_gen.py [--data training/data/vla_v1] [--out training/RL/map/include/vla_vocab.h]

Inputs: names.jsonl / name128.f16 (vla_tables.py), app128.f16 / app_views.f16 (C++ training/BC/tools/app_table).
Name confidence (VLA_INPUT 3절 "이름 확신도 2 = 라벨 표 1위 점수, 1위 − 2위") for appearance row a (0..5 = gmap::Cls, 6 = ghost) reported
under sim class name c:  conf1 = cos(app128[a], name128[sim_name(c)]),  conf2 = conf1 − max cos(app128[a], v) over the naming vocabulary
outside c's synonym group. Naming vocabulary = every vla_v1 name row except hypernym rows and held-out (§7 eval) rows: sim classes +
their training synonyms + all BEHAVIOR 2026 categories/synonyms — i.e. the labels a detector could output in our curriculum.
Map tokens put the hypernym row instead of sim_name(c) when conf2 < kConfLow.
"""
import os, json, hashlib, argparse, datetime
import numpy as np

KCONF_LOW = -0.08   # see choose_threshold() printout: all ghost (false-positive) table entries fall back, the best-separated correct ones keep


def hexf(x): return float(np.float32(x)).hex() + 'f' if float(np.float32(x)) != 0 else '0.0f'


def sha(p):
    h = hashlib.sha256(); h.update(open(p, 'rb').read()); return h.hexdigest()


def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--data', default='training/data/vla_v1')
    ap.add_argument('--out', default='training/RL/map/include/vla_vocab.h'); a = ap.parse_args()
    R = [json.loads(l) for l in open(f'{a.data}/names.jsonl')]; N = len(R)
    V = np.fromfile(f'{a.data}/name128.f16', np.float16).astype(np.float32).reshape(N, 128)
    A = np.fromfile(f'{a.data}/app128.f16', np.float16).astype(np.float32).reshape(7, 128)
    AV = np.fromfile(f'{a.data}/app_views.f16', np.float16).astype(np.float32).reshape(7, -1, 128)
    voc = np.array([r['kind'] != 'hyper' and not r['heldout'] for r in R]); grp = np.array([r['group'] for r in R])
    sim = [next(r['i'] for r in R if r['kind'] == 'sim' and r['group'] == g) for g in range(6)]
    hyp = [R[s]['hyper'] for s in sim]

    def conf(v, c):
        s = V @ v; c1 = s[sim[c]]; return c1, c1 - s[voc & (grp != c)].max()
    C1 = np.array([[conf(A[r], c)[0] for c in range(6)] for r in range(7)], np.float32)
    C2 = np.array([[conf(A[r], c)[1] for c in range(6)] for r in range(7)], np.float32)
    # per-view distribution (the table rows are view means; this is the spread behind the threshold)
    dist = {}
    for name, sel in (('correct', lambda r, c: r == c and r < 6), ('wrong', lambda r, c: r != c and r < 6), ('ghost', lambda r, c: r == 6)):
        x = np.array([conf(v / np.linalg.norm(v), c)[1] for r in range(7) for v in AV[r] for c in range(6) if sel(r, c)])
        dist[name] = [round(float(q), 4) for q in np.percentile(x, [5, 25, 50, 75, 95])]
    d, off = np.diag(C2[:6]), C2[:6][~np.eye(6, dtype=bool)]
    fall = dict(correct_kept=int((d >= KCONF_LOW).sum()), wrong_to_hyper=int((off < KCONF_LOW).sum()), ghost_to_hyper=int((C2[6] < KCONF_LOW).sum()))
    top1 = []
    for r in range(7):
        s = np.where(voc, V @ A[r], -9); top1.append(R[int(np.argmax(s))]['en'])
    print('conf2 per-view percentiles 5/25/50/75/95:', dist); print('table entries with kConfLow', KCONF_LOW, fall); print('label-table top-1 per app row:', top1)
    # manifest
    man = json.load(open(f'{a.data}/manifest.json'))
    man['app'] = dict(rows=['cup', 'box', 'chair', 'table', 'cabinet', 'trash can', 'ghost (background crop)'],
                      tool='training/BC/tools/app_table (team RenderBatch cheap profile, C++ SigLIP 2 B/32-256 tower FP16, C++ MAP pool + embed head h double)',
                      views_per_row=int(AV.shape[1]), label_top1=top1)
    man['conf'] = dict(vocab='vla_v1 rows minus hypernym and held-out rows', kConfLow=KCONF_LOW, conf2_view_percentiles=dist, table_entries=fall)
    fs = {f: sha(f'{a.data}/{f}') for f in sorted(os.listdir(a.data)) if f != 'manifest.json'}
    man['files'] = fs; man['sha'] = hashlib.sha256(''.join(fs[k] for k in sorted(fs)).encode()).hexdigest()[:16]
    json.dump(man, open(f'{a.data}/manifest.json', 'w'), indent=1, ensure_ascii=False)
    # header
    def arr1(x): return '{' + ', '.join(str(int(v)) for v in x) + '}'
    def arr2(M): return '{' + ', '.join('{' + ', '.join(hexf(v) for v in row) + '}' for row in M) + '}'
    sim_en = ', '.join(R[s]['en'] for s in sim); hyp_en = ', '.join(R[h]['en'] for h in hyp)
    txt = f'''// GENERATED by training/embed/vla_vocab_gen.py from training/data/vla_v1 (manifest sha {man["sha"]}, {datetime.date.today().isoformat()}) — do not edit.
// VLA_INPUT 3절 이름 뜻 벡터·이름 확신도의 장치 표(지도 토큰용, CPU·GPU 같은 값). 벡터 자체(name128.f16·app128.f16)는 런타임 파일로 읽는다.
//   sim_name(cls)  : gmap::Cls → name128 행 ({sim_en})
//   sim_hyper(cls) : 확신이 낮을 때 쓰는 상위어 행 ({hyp_en})
//   conf1(app, cls): cos(app128[app], name128[sim_name(cls)]),  conf2 = conf1 − (이름 어휘에서 cls 동의어 묶음 밖 최대 코사인)
//                    app = 0..5 gmap::Cls(그 물체의 생김새), 6 = 유령(가짜 검출 — 바닥·벽 조각)
//   kConfLow       : conf2 < kConfLow 이면 지도 토큰 이름 = sim_hyper(cls)
#pragma once
#include <cstdint>

namespace vlav {{

constexpr int N_NAME = {N};
constexpr int N_APP = 7;
constexpr int DIM = 128;
constexpr float kConfLow = {hexf(KCONF_LOW)};

#define VLAV_SIM_NAME {arr1(sim)}
#define VLAV_SIM_HYPER {arr1(hyp)}
#define VLAV_CONF1 {arr2(C1)}
#define VLAV_CONF2 {arr2(C2)}

constexpr int16_t kSimName[6] = VLAV_SIM_NAME;
constexpr int16_t kSimHyper[6] = VLAV_SIM_HYPER;
constexpr float kConf1[7][6] = VLAV_CONF1;
constexpr float kConf2[7][6] = VLAV_CONF2;
#ifdef __CUDACC__
static __constant__ int16_t kSimNameDev[6] = VLAV_SIM_NAME;
static __constant__ int16_t kSimHyperDev[6] = VLAV_SIM_HYPER;
static __constant__ float kConf1Dev[7][6] = VLAV_CONF1;
static __constant__ float kConf2Dev[7][6] = VLAV_CONF2;
#define VLAV_FN __host__ __device__ __forceinline__
#else
#define VLAV_FN inline
#endif

VLAV_FN int16_t sim_name(int cls) {{
#ifdef __CUDA_ARCH__
  return kSimNameDev[cls];
#else
  return kSimName[cls];
#endif
}}
VLAV_FN int16_t sim_hyper(int cls) {{
#ifdef __CUDA_ARCH__
  return kSimHyperDev[cls];
#else
  return kSimHyper[cls];
#endif
}}
VLAV_FN float conf1(int app, int cls) {{
#ifdef __CUDA_ARCH__
  return kConf1Dev[app][cls];
#else
  return kConf1[app][cls];
#endif
}}
VLAV_FN float conf2(int app, int cls) {{
#ifdef __CUDA_ARCH__
  return kConf2Dev[app][cls];
#else
  return kConf2[app][cls];
#endif
}}

#undef VLAV_FN
#undef VLAV_SIM_NAME
#undef VLAV_SIM_HYPER
#undef VLAV_CONF1
#undef VLAV_CONF2

}}  // namespace vlav
'''
    open(a.out, 'w').write(txt)
    print('wrote', a.out, 'N_NAME', N, 'sim rows', sim, 'hyper rows', hyp, 'sha', man['sha'])


if __name__ == '__main__':
    main()
