// GENERATED by urdf2hdr from map_vla.urdf — do not edit by hand (regenerate: training/RL/tools/urdf2hdr).
// Joint tree of the LIMO + OMX-F robot. Each fixed transform = origin(xyz, rpy) as a row-major 3x3 rotation (computed in f64, stored as float) + translation.
#pragma once
namespace limo_omx {

enum JointKind { kFixed = 0, kRevolute = 1, kContinuous = 2 };
struct JointConst { int kind; float R[9]; float t[3]; float axis[3]; float lower, upper, vel_max; };   // names: see the J_* indices below

constexpr int kNumJoints = 24;
#define LIMO_OMX_JOINT_TABLE \
    { \
    /* base_joint */ {kFixed, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}, {0.0f, 0.0f, 0.15f}, {0.0f, 0.0f, 1.0f}, 0.0f, 0.0f, 0.0f}, \
    /* inertial_joint */ {kFixed, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}, {0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 1.0f}, 0.0f, 0.0f, 0.0f}, \
    /* laser_joint */ {kFixed, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}, {0.103f, 0.0f, -0.034f}, {0.0f, 0.0f, 1.0f}, 0.0f, 0.0f, 0.0f}, \
    /* depth_camera_joint */ {kFixed, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}, {0.084f, 0.0f, 0.03f}, {0.0f, 0.0f, 1.0f}, 0.0f, 0.0f, 0.0f}, \
    /* depth_camera_to_camera_joint */ {kFixed, {1.3267949e-6f, 1.3267949e-6f, 1.0f, -1.0f, 0.0f, 1.3267949e-6f, 0.0f, -1.0f, 1.3267949e-6f}, {0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 1.0f}, 0.0f, 0.0f, 0.0f}, \
    /* imu_joint */ {kFixed, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}, {0.0f, 0.0f, -0.1f}, {0.0f, 0.0f, 1.0f}, 0.0f, 0.0f, 0.0f}, \
    /* front_left_wheel */ {kContinuous, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}, {0.1f, 0.065f, -0.1f}, {0.0f, 1.0f, 0.0f}, 0.0f, 0.0f, 0.0f}, \
    /* front_right_wheel */ {kContinuous, {1.0f, 0.0f, 0.0f, 0.0f, -1.0f, -2.6535897e-6f, 0.0f, 2.6535897e-6f, -1.0f}, {0.1f, -0.065f, -0.1f}, {0.0f, -1.0f, 0.0f}, 0.0f, 0.0f, 0.0f}, \
    /* rear_left_wheel */ {kContinuous, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}, {-0.1f, 0.065f, -0.1f}, {0.0f, 1.0f, 0.0f}, 0.0f, 0.0f, 0.0f}, \
    /* rear_right_wheel */ {kContinuous, {1.0f, 0.0f, 0.0f, 0.0f, -1.0f, -2.6535897e-6f, 0.0f, 2.6535897e-6f, -1.0f}, {-0.1f, -0.065f, -0.1f}, {0.0f, -1.0f, 0.0f}, 0.0f, 0.0f, 0.0f}, \
    /* omx_joint1 */ {kRevolute, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}, {-0.01125f, 0.0f, 0.034f}, {0.0f, 0.0f, 1.0f}, -4.712389f, 6.283185f, 4.8f}, \
    /* omx_joint2 */ {kRevolute, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}, {0.0f, 0.0f, 0.0635f}, {0.0f, 1.0f, 0.0f}, -2.094395f, 1.570796f, 4.8f}, \
    /* omx_joint3 */ {kRevolute, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}, {0.0415f, 0.0f, 0.11315f}, {0.0f, 1.0f, 0.0f}, -2.094395f, 1.570796f, 4.8f}, \
    /* omx_joint4 */ {kRevolute, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}, {0.162f, 0.0f, 0.0f}, {0.0f, 1.0f, 0.0f}, -1.745329f, 1.745329f, 4.8f}, \
    /* omx_joint5 */ {kRevolute, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}, {0.0287f, 0.0f, 0.0f}, {1.0f, 0.0f, 0.0f}, -4.712389f, 4.712389f, 4.8f}, \
    /* omx_gripper_joint_1 */ {kRevolute, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}, {0.0295f, 0.0075f, 0.0f}, {0.0f, 0.0f, 1.0f}, 0.0f, 1.745329f, 4.8f}, \
    /* omx_gripper_joint_2 */ {kRevolute, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}, {0.0295f, -0.0108f, 0.0f}, {0.0f, 0.0f, 1.0f}, -1.745329f, 0.0f, 4.8f}, \
    /* depth_camera_lens_joint */ {kFixed, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}, {0.01f, 0.0f, 0.0f}, {0.0f, 0.0f, 1.0f}, 0.0f, 0.0f, 0.0f}, \
    /* depth_camera_lens_optical_joint */ {kFixed, {2.6794897e-8f, 2.6794897e-8f, 1.0f, -1.0f, 0.0f, 2.6794897e-8f, 0.0f, -1.0f, 2.6794897e-8f}, {0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 1.0f}, 0.0f, 0.0f, 0.0f}, \
    /* omx_mount_joint */ {kFixed, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}, {-0.04f, 0.0f, 0.0f}, {0.0f, 0.0f, 1.0f}, 0.0f, 0.0f, 0.0f}, \
    /* omx_end_effector_joint */ {kFixed, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}, {0.09193f, -0.0016f, 0.0f}, {0.0f, 0.0f, 1.0f}, 0.0f, 0.0f, 0.0f}, \
    /* grasp_point_joint */ {kFixed, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f}, {0.08003f, -0.0016f, 0.0f}, {0.0f, 0.0f, 1.0f}, 0.0f, 0.0f, 0.0f}, \
    /* wrist_cam_joint */ {kFixed, {0.7886906f, 0.0f, 0.61479026f, 0.0f, 1.0f, 0.0f, -0.61479026f, 0.0f, 0.7886906f}, {0.0498f, 0.0f, 0.0351f}, {0.0f, 0.0f, 1.0f}, 0.0f, 0.0f, 0.0f}, \
    /* wrist_cam_optical_joint */ {kFixed, {2.6794897e-8f, 2.6794897e-8f, 1.0f, -1.0f, 0.0f, 2.6794897e-8f, 0.0f, -1.0f, 2.6794897e-8f}, {0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 1.0f}, 0.0f, 0.0f, 0.0f}, \
    }

constexpr JointConst kJoints[kNumJoints] = LIMO_OMX_JOINT_TABLE;   // host
#ifdef __CUDACC__
static __constant__ JointConst kJointsDev[kNumJoints] = LIMO_OMX_JOINT_TABLE;   // device (the same table)
#endif
#ifdef __CUDACC__
__host__ __device__ __forceinline__
#else
inline
#endif
const JointConst& joint(int j) {
#ifdef __CUDA_ARCH__
  return kJointsDev[j];
#else
  return kJoints[j];
#endif
}

// joint indices by name
constexpr int J_BASE_JOINT = 0;   // base_footprint -> base_link (fixed)
constexpr int J_INERTIAL_JOINT = 1;   // base_link -> inertial_link (fixed)
constexpr int J_LASER_JOINT = 2;   // base_link -> laser_link (fixed)
constexpr int J_DEPTH_CAMERA_JOINT = 3;   // base_link -> depth_camera_link (fixed)
constexpr int J_DEPTH_CAMERA_TO_CAMERA_JOINT = 4;   // depth_camera_link -> depth_link (fixed)
constexpr int J_IMU_JOINT = 5;   // base_link -> imu_link (fixed)
constexpr int J_FRONT_LEFT_WHEEL = 6;   // base_link -> front_left_wheel_link (continuous)
constexpr int J_FRONT_RIGHT_WHEEL = 7;   // base_link -> front_right_wheel_link (continuous)
constexpr int J_REAR_LEFT_WHEEL = 8;   // base_link -> rear_left_wheel_link (continuous)
constexpr int J_REAR_RIGHT_WHEEL = 9;   // base_link -> rear_right_wheel_link (continuous)
constexpr int J_OMX_JOINT1 = 10;   // omx_link0 -> omx_link1 (revolute)
constexpr int J_OMX_JOINT2 = 11;   // omx_link1 -> omx_link2 (revolute)
constexpr int J_OMX_JOINT3 = 12;   // omx_link2 -> omx_link3 (revolute)
constexpr int J_OMX_JOINT4 = 13;   // omx_link3 -> omx_link4 (revolute)
constexpr int J_OMX_JOINT5 = 14;   // omx_link4 -> omx_link5 (revolute)
constexpr int J_OMX_GRIPPER_JOINT_1 = 15;   // omx_link5 -> omx_link6 (revolute)
constexpr int J_OMX_GRIPPER_JOINT_2 = 16;   // omx_link5 -> omx_link7 (revolute)
constexpr int J_DEPTH_CAMERA_LENS_JOINT = 17;   // depth_camera_link -> depth_camera_lens_link (fixed)
constexpr int J_DEPTH_CAMERA_LENS_OPTICAL_JOINT = 18;   // depth_camera_lens_link -> depth_camera_lens_optical_frame (fixed)
constexpr int J_OMX_MOUNT_JOINT = 19;   // base_link -> omx_link0 (fixed)
constexpr int J_OMX_END_EFFECTOR_JOINT = 20;   // omx_link5 -> omx_end_effector_link (fixed)
constexpr int J_GRASP_POINT_JOINT = 21;   // omx_link5 -> grasp_point (fixed)
constexpr int J_WRIST_CAM_JOINT = 22;   // omx_link5 -> wrist_cam_link (fixed)
constexpr int J_WRIST_CAM_OPTICAL_JOINT = 23;   // wrist_cam_link -> wrist_cam_optical_frame (fixed)

}  // namespace limo_omx
