<?xml version="1.0"?>
<package format="3">
  <name>map_vla_description</name>
  <version>0.0.1</version>
  <description>LIMO + OMX-F mobile manipulator description (TF tree) for Map_Vla</description>
  <maintainer email="juyoung020@users.noreply.github.com">juyoung</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>limo_description</exec_depend>
  <exec_depend>open_manipulator_description</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
